language: node_js # 设置语言
node_js:  stable # 设置相应版本
    #- "11.11.0"
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
install:
    - npm install # 安装hexo及插件
before_install:
    - export TZ='Asia/Shanghai' # 更改时区
    - npm install hexo-cli -g  # 安装hexo环境
      #- npm uninstall hexo-renderer-scss 
    - npm install hexo-generator-searchdb --save
    - npm uninstall hexo-baidu-url-submit --remove #添加百度提交插件
    - chmod +x ./publish-to-gh-pages.sh  # 为shell文件添加可执行权限
after_script:
    - ./publish-to-gh-pages.sh
script:
    #- hexo clean # 清除
    - hexo g # 生成
branches:
    only:
        - dev # 只监测hexo分支
env:
    global:
        # Github Pages
        - GH_REF: github.com/luochenxi/luochenxi.github.io.git #设置GH_REF，注意更改成自己的仓库地址
        # Coding Pages https://git.coding.net/hadronw/hadronw.git
        #- CO_REF: git.coding.net/hadronw/hadronw.git
         # gitlab https://gitlab.com/hadronw/hadronw.git
         #- GL_REE: gitlab.com/hadronw/hadronw.git
